server:
  port: 999
  
spring:
  datasource:
    druid:
      url: jdbc:mysql://192.168.10.120:3306/partition_test
      # 根据url自动识别。这一项可配可不配，如果不配置druid会根据url自动识别dbType，然后选择相应的driverClassName
      driver-class-name: com.mysql.jdbc.Driver
      username: ssy
      password: 123456
      # 初始化时建立物理连接的个数。初始化发生在显式调用init方法，或者第一次getConnection时
      initial-size: 8
      min-idle: 8
      # 最大连接池数量
      max-active: 20
      # 获取连接时最大等待时间，单位毫秒。配置了maxWait之后，缺省启用公平锁，并发效率会有所下降，如果需要可以通过配置useUnfairLock属性为true使用非公平锁。
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      #检测连接是否有效的sql
      validation-query: SELECT 1
      validation-query-timeout: 60000
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 连接池中的minIdle数量以内的连接，空闲时间超过minEvictableIdleTimeMillis，则会执行keepAlive操作。
      keep-alive: false
      # 默认1分钟，有两个含义：
      # 1) Destroy线程会检测连接的间隔时间，如果连接空闲时间大于等于minEvictableIdleTimeMillis则关闭物理连接。
      # 2) testWhileIdle的判断依据，详细看testWhileIdle属性的说明
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间,30分钟
      min-evictable-idle-time-millis: 1800000
      # PSCache Mysql下建议关闭
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
